import { TextbookChapter } from '../types';

export const INITIAL_TEXTBOOK: {
  title: string;
  subtitle: string;
  author: string;
  description: string;
  chapters: TextbookChapter[];
} = {
  title: 'The Iris Number System',
  subtitle: 'An Unnumbered AsciiDoc / LatexMath Treatise on Unified Multi-Algebra',
  author: 'Counting-Iris Mathematical Foundation',
  description: 'A formal axiomatic development of the Counting-Iris Number System unifying discrete arithmetic, Clifford Algebra Cl(4,1,1), Nonstandard Analysis (*R), Jaynesian Maximum Entropy, and tautological proofs in number theory.',
  chapters: [
    {
      id: 'chap-integers',
      title: 'The Integers',
      summary: 'Foundational definition of the discrete integer domain Z, its canonical scalar embedding into Clifford Algebra Cl(4,1,1), and the essential postulates governing the tautological structure.',
      sections: [
        {
          id: 'sec-integers-def',
          title: 'Definition of the Integers',
          contentAsciiDoc: `
== Definition of the Integers

The domain of **Integers**, denoted by \\(\\mathbb{Z}\\), forms the discrete algebraic backbone of the Counting-Iris Number System. In standard arithmetic, \\(\\mathbb{Z}\\) is defined as the set of equivalence classes of ordered pairs of natural numbers under the relation \\((a,b) \\sim (c,d) \\iff a+d = b+c\\).

Within the **Counting-Iris framework**, the integers are constructed as the minimal discrete subring generated by the multiplicative identity \\(\\mathbf{1}\\) and its additive inverse \\(-\\mathbf{1}\\) under successor iterations:

\\[
\\mathbb{Z} = \\{ \\dots, -3\\mathbf{1}, -2\\mathbf{1}, -\\mathbf{1}, \\mathbf{0}, \\mathbf{1}, 2\\mathbf{1}, 3\\mathbf{1}, \\dots \\}
\\]

In this framework, every integer \\(n \\in \\mathbb{Z}\\) acts both as a discrete scalar multiplicity and as a discrete projection operator upon the continuous spectrum of the Iris basis \\(\\{1, \\iota, \\varpi, \\vartheta\\}\\).

[NOTE]
====
In the Counting-Iris Number System, chapters and sections are un-numbered to emphasize conceptual cohesion and non-hierarchical tautological deduction over rigid ordinal indexing.
====
`
        },
        {
          id: 'sec-integers-postulates',
          title: 'Postulates of the Tautological Structure',
          contentAsciiDoc: `
== Postulates of the Tautological Structure

To establish the tautological engine of the Iris Number System starting strictly from the integers \\(\\mathbb{Z}\\), we postulate the following foundational axioms:

[POSTULATE]
.Postulate 1: Successor Order and Discrete Ring Properties
====
The domain \\((\\mathbb{Z}, +, \\cdot, \\le)\\) is a totally ordered commutative ring with no zero divisors, generated by the discrete successor operator \\(S(n) = n + \\mathbf{1}\\). For every non-zero integer \\(n \\in \\mathbb{Z}\\setminus\\{0\\}\\), the absolute value \\(|n| \\ge 1\\) guarantees a discrete gap.
====

[POSTULATE]
.Postulate 2: Canonical Scalar Embedding into Clifford Algebra Cl(4,1,1)
====
There exists a canonical ring monomorphism embedding the integers into the grade-0 scalar subalgebra of the 6-generator Clifford algebra \\(Cl(4,1,1)\\) with metric signature \\((++++,-,0)\\):

\\[
\\iota_0: \\mathbb{Z} \\hookrightarrow Cl(4,1,1), \\quad n \\mapsto n \\cdot \\mathbf{1}_{Cl}
\\]

where \\(\\mathbf{1}_{Cl}\\) is the Clifford unit scalar element satisfying \\(\\mathbf{1}_{Cl} e_A = e_A \\mathbf{1}_{Cl} = e_A\\) for all basis elements \\(e_A\\).
====

[POSTULATE]
.Postulate 3: Metric Preservation of Quadratic Forms
====
For any discrete tuple \\((a,b) \\in \\mathbb{Z}^2\\), the Clifford metric norm over orthogonal basis generators \\(e_1, e_2\\) preserves exact integer quadratic forms:

\\[
\\|a e_1 + b e_2\\|^2 = (a e_1 + b e_2)(a e_1 + b e_2)^\dagger = a^2 + b^2 \\in \\mathbb{Z}_{\\ge 0}
\\]

This guarantees that diophantine norm equations in \\(\\mathbb{Z}\\) map directly into geometric invariants of \\(Cl(4,1,1)\\).
====

[POSTULATE]
.Postulate 4: Bivector Parity Duality
====
Every integer \\(n \\in \\mathbb{Z}\\) possesses a canonical parity projection into the bivector subalgebra \\(e_{23}, e_{31}, e_{12}\\) (isomorphic to quaternions \\(\\mathbf{H}\\)). Even integers \\(n = 2k\\) yield zero bivector commutator residue, whereas odd integers \\(n = 2k+1\\) yield a unit parity residue \\(e_{23} \\wedge e_{31}\\).
====

[POSTULATE]
.Postulate 5: Nonstandard Extension via Transfer
====
Under ultrafilter extension, the standard integers \\(\\mathbb{Z}\\) extend tautologically to the nonstandard integers \\({}^*\\mathbb{Z}\\) embedded in \\({}^*\\mathbb{R}\\). The extension introduces infinite nonstandard integers \\(\\omega \\in {}^*\\mathbb{Z} \\setminus \\mathbb{Z}\\) and exact infinitesimals \\(\\epsilon = 1/\\omega\\), satisfying the Transfer Principle:

\\[
\\forall n \\in \\mathbb{Z}, \\quad n < \\omega \\quad \\text{and} \\quad \\epsilon \\cdot \\omega = 1
\\]
====

[POSTULATE]
.Postulate 6: Jaynesian Maximum Entropy Prior
====
Any probability measure \\(P(n)\\) assigned over discrete integer states \\(n \\in \\mathbb{Z}\\) under expectation constraint \\(\\langle A(n) \\rangle = a\\) maximizes the Shannon-Jaynes entropy:

\\[
S[P] = -\\sum_{n \\in \\mathbb{Z}} P(n) \\ln P(n)
\\]

yielding the canonical unbiased prior distribution \\(P(n) = \\frac{1}{Z} e^{-\\lambda A(n)}\\).
====
`
        },
        {
          id: 'sec-integers-clifford',
          title: 'Clifford Algebra Integration and Parity Algebra',
          contentAsciiDoc: `
== Clifford Algebra Integration and Parity Algebra

Through Postulate 2 and Postulate 4, integer arithmetic in \\(\\mathbb{Z}\\) is not merely isolated symbolic counting, but a projection of geometric operations in \\(Cl(4,1,1)\\).

Let \\(n, m \\in \\mathbb{Z}\\). Consider their representation as bivector-graded multivectors:

\\[
M(n) = n \\cdot \\mathbf{1}_{Cl} + \\frac{1 - (-1)^n}{2} e_{12}
\\]

When \\(n\\) is even, \\(M(n) = n \\mathbf{1}_{Cl}\\) is purely scalar. When \\(n\\) is odd, \\(M(n) = n \\mathbf{1}_{Cl} + e_{12}\\) acquires a unit bivector component whose square is \\(e_{12}^2 = -1\\).

[THEOREM]
.Theorem: Parity Conservation in Geometric Products
====
For any two integers \\(n, m \\in \\mathbb{Z}\\), the geometric product \\(M(n) M(m)\\) preserves the additive parity rule in \\(\\mathbb{Z}\\):

\\[
\\text{Grade}_2\\left( M(n) M(m) \\right) \\neq 0 \\iff n+m \\equiv 1 \\pmod 2
\\]
====

This algebraic duality provides the structural foundation for proving parity-based number theory conjectures (such as Goldbach's Partition Problem) without relying on heuristic approximations.
`
        }
      ]
    }
  ]
};

export function generateFullAsciiDoc(textbook = INITIAL_TEXTBOOK): string {
  let adoc = `= ${textbook.title}\n`;
  adoc += `:author: ${textbook.author}\n`;
  adoc += `:toc: left\n`;
  adoc += `:toc-title: Table of Contents\n`;
  adoc += `:stem: latexmath\n`;
  adoc += `:sectnums!:\n\n`; // Chapters and sections are not numbered, only named!
  adoc += `${textbook.description}\n\n`;

  textbook.chapters.forEach((chap) => {
    adoc += `= ${chap.title}\n\n`; // Un-numbered chapter name
    if (chap.summary) {
      adoc += `${chap.summary}\n\n`;
    }
    chap.sections.forEach((sec) => {
      adoc += `${sec.contentAsciiDoc.trim()}\n\n`;
    });
  });

  return adoc;
}
